- hosts: "{{ groups['bastion'] | sort | first }}"
  become: true
  roles:
    - role: mojaloop.iac.argocd
      vars:
        teardown: true

- hosts: agent
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s
    - role: mojaloop.iac.netbird_client

- hosts: master
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s
    - role: mojaloop.iac.netbird_client