- hosts: agent
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s
    - role: mojaloop.iac.netbird_client

- hosts: master
  become: true
  vars:
    teardown: true
  roles:
    - role: mojaloop.iac.microk8s
    - role: mojaloop.iac.netbird_client