- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    #- mojaloop.iac.eks_cleanup

- hosts: "{{ groups['bastion'] | sort | first }}"
  become: true
  roles:
    - mojaloop.iac.eks_util
    - geerlingguy.k8s.helm
    - mojaloop.iac.argocd
    #- mojaloop.iac.eks_cleanup

- name: Create Test Harness
  import_playbook: test_harness_deploy.yaml
