- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    - mojaloop.iac.netbird_client

- hosts: master
  become: true
  roles:
    - mojaloop.iac.k8s_node_common
    - mojaloop.iac.netbird_client

- hosts: agent
  become: true
  roles:
    - mojaloop.iac.k8s_node_common
    - mojaloop.iac.netbird_client

- hosts: master
  become: true
  roles:
    - role: mojaloop.iac.microk8s
      vars:
        microk8s_enable_ha: true
        microk8s_group_ha: "master"
        microk8s_group_workers: "agent"
        add_workers_to_hostfile: true

- hosts: master
  become: true
  tasks:
    - name: patch calico
      ansible.builtin.import_role:
        name: mojaloop.iac.microk8s
        tasks_from: patch-calico

- hosts: master
  become: true
  tasks:
    - name: write current oidc config
      ansible.builtin.import_role:
        name: mojaloop.iac.microk8s
        tasks_from: configure-oidc

- hosts: agent
  become: true
  roles:
    - role: mojaloop.iac.microk8s
      vars:
        microk8s_enable_ha: true
        microk8s_group_ha: "master"
        microk8s_group_workers: "agent"

- hosts: "{{ groups['bastion'] | sort | first }}"
  become: true
  roles:
    - geerlingguy.k8s.helm
    - mojaloop.iac.argocd

- name: Create Test Harness
  import_playbook: test_harness_deploy.yaml
