- hosts: bastion
  become: true
  roles:
    - mojaloop.iac.bastion_common
    - mojaloop.iac.docker

- hosts: master
  become: true
  roles:
    - role: mojaloop.iac.k8s_node_common

- hosts: agent
  become: true
  roles:
    - role: mojaloop.iac.k8s_node_common

- hosts: master
  become: true
  roles:
    - role: mojaloop.iac.microk8s
      vars:
        microk8s_enable_ha: true
        microk8s_group_ha: "master"
        microk8s_group_workers: "agent"
        add_workers_to_hostfile: true
        microk8s_plugins: {}
- hosts: agent
  become: true
  roles:
    - role: mojaloop.iac.microk8s
      vars:
        microk8s_enable_ha: true
        microk8s_group_ha: "master"
        microk8s_group_workers: "agent"

- hosts: "{{ groups['bastion'] | sort | first }}"
  become: true
  roles:
    - role: geerlingguy.k8s.helm
      vars:
        helm_version: "v3.14.0"
    - role: mojaloop.iac.cc_k8s
      vars:
        helm_version: "3.14.0"

- hosts: bastion
  become: true
  roles:
    - role: mojaloop.iac.netbird_client
      vars:
        netbird_api_host: "{{ hostvars[groups['bastion'][0]]['fact_netbird_management_url'] }}"
        netbird_setup_key: "{{ hostvars[groups['bastion'][0]]['fact_bastion_netbird_setup_key'] }}"

- hosts: master
  become: true
  tasks:
    - name: write current oidc config
      ansible.builtin.import_role:
        name: mojaloop.iac.microk8s
        tasks_from: configure-oidc
      vars:
        kubernetes_oidc_enabled: true
        kubernetes_oidc_issuer: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_issuer'] }}"
        kubernetes_oidc_client_id: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_client_id'] }}"
        kubernetes_oidc_groups_claim: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_groups_claim'] }}"
        kubernetes_oidc_groups_prefix: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_groups_prefix'] }}"
        kubernetes_oidc_username_prefix: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_username_prefix'] }}"
        kubernetes_oidc_username_claim: "{{ hostvars[groups['bastion'][0]]['kubernetes_oidc_username_claim'] }}"
