---
# tasks file for netbird_client
- name: setup netbird install
  shell: |
    curl -sSL https://pkgs.netbird.io/debian/public.key | gpg --yes --dearmor --output /usr/share/keyrings/netbird-archive-keyring.gpg
    echo 'deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main' | tee /etc/apt/sources.list.d/netbird.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Netbird CLI
  package:
    name:
      - netbird={{ netbird_version }}

- name: unjoin the node from old netbird in case of migratinon
  command: netbird down
  when: migrate

- name: join the node to netbird
  command:  netbird up -k {{ netbird_setup_key }} -m {{ netbird_api_host }}
