---
- name: Find the designated master host
  ansible.builtin.set_fact:
    designated_master_host: "{{ (groups[microk8s_group_ha]|sort)[0] }}"

- name: Debug current addons
  shell: microk8s status | grep "dns"
  register: dns_status
- debug:
    var: dns_status.stdout

- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: "/root/.kube/config"
    dest: "{{ kubeconfig_local_location }}/kubeconfig"
    flat: yes
  when: inventory_hostname == designated_master_host

- name: Debug current addons
  shell: microk8s status | grep "dns"
  register: dns_status
- debug:
    var: dns_status.stdout

- name: Replace IP with LB in kubeconfig
  ansible.builtin.shell: |
    yq e -i  '.clusters[0].cluster.server = "https://{{kubeapi_loadbalancer_fqdn}}:{{microk8s_apiserver_port}}"' "{{ kubeconfig_local_location }}/kubeconfig"
    yq e -i  '.clusters[0].name = "{{base_domain}}-cluster"' "{{ kubeconfig_local_location }}/kubeconfig"
    yq e -i  '.contexts[0].name = "{{base_domain}}"' "{{ kubeconfig_local_location }}/kubeconfig"
    yq e -i  '.contexts[0].context.cluster = "{{base_domain}}-cluster"' "{{ kubeconfig_local_location }}/kubeconfig"
    yq e -i  '.current-context = "{{base_domain}}"' "{{ kubeconfig_local_location }}/kubeconfig"
  when: kubeapi_loadbalancer_fqdn != "none"
  delegate_to: localhost
  delegate_facts: true