# for on premise installations
- name: Reset microk8s
  become: true
  ansible.builtin.command: "microk8s reset"
  ignore_errors: true

- name: Remove microk8s
  become: true
  ansible.builtin.command: "snap remove --purge microk8s"
  ignore_errors: true

- name: Remove microk8s data
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ microk8s_root_path }}"

- name: Remove longhorn data
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ longhorn_data_path }}"

- name: Remove rook data
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ rook_data_path }}"

- name: reset rook vol
  become: true
  shell: |
    wipefs -a {{ rook_disk_vol }}
    dd if=/dev/zero of="{{ rook_disk_vol }}" bs=1M count=100 oflag=direct,dsync
    partprobe {{ rook_disk_vol }}
  when: enable_rook_disk_reset | bool
