argocd_version: "2.13.1"
argocd_lovely_plugin_version: "0.18.0"
repo_url: "https://localhost/repo.git"
repo_password: mypassword
repo_username: user
external_secrets_version: "0.9.0"
external_secrets_namespace: "external-secrets"
tenant_vault_token: token
tenant_vault_server_url: "https://tenantvault"
kubeconfig_location: "/root/.kube"
root_app_path: "infra/app-yamls"
netmaker_image_version: "0.24.0"
wireguard_node_port: "31821"
cluster_name: envname
kubeconfig_local_location: "/tmp"
kustomize_version: "3.2.3"
kubectl_version: "1.24.6"
coredns_version: "1.28.2"
coredns_max_scale: 10
install_nodelocaldns: false
gitlab_oidc_issuer: http://issuer-fqdn
argocd_fqdn: example.com
oidc_admin_group: tenant-admins
kubernetes_oidc_k8s_user_group: none
kubernetes_oidc_k8s_admin_group: none
kubernetes_oidc_enabled: false
kubernetes_oidc_issuer: none
kubernetes_oidc_client_id: none
install_coredns: true
coredns_localcache_version: "1.11.3"
dns_bind_address: "169.254.20.10"